name: english_quiz
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

#  assets:
#    - assets/images/
#    - assets/icons/
#    - assets/sounds/
##    - assets/data/vocabulary/beginner
#    - assets/data/grammar/
#    - assets/data/spelling/
#    - assets/data/kids/
#    - assets/data/reading/
#    - assets/data/phrasal_verbs/
#    - assets/data/
  assets:
    - assets/data/vocabulary/beginner/
    - assets/data/vocabulary/intermediate/
    - assets/data/vocabulary/advanced/
    - assets/data/phrasal_verbs/beginner/
    - assets/data/phrasal_verbs/intermediate/
    - assets/data/phrasal_verbs/advanced/
    - assets/data/reading/beginner/
    - assets/data/reading/intermediate/
    - assets/data/reading/advanced/
    - assets/data/grammar/beginner/
    - assets/data/grammar/intermediate/
    - assets/data/grammar/advanced/
    - assets/data/kids/beginner/
    - assets/data/kids/intermediate/
    - assets/data/kids/advanced/
    - assets/data/spelling/beginner/
    - assets/data/spelling/intermediate/
    - assets/data/spelling/advanced/
    - assets/data/toefl/reading/quiz1.json
    - assets/data/toefl/reading/quiz2.json
    - assets/data/toefl/reading/quiz3.json
    - assets/data/toefl/reading/quiz4.json
    - assets/data/toefl/reading/quiz5.json
    - assets/data/toefl/vocabulary/quiz1.json
    - assets/data/toefl/vocabulary/quiz2.json
    - assets/data/toefl/vocabulary/quiz3.json
    - assets/data/toefl/vocabulary/quiz4.json
    - assets/data/toefl/vocabulary/quiz5.json
    - assets/data/toefl/grammar/quiz1.json
    - assets/data/toefl/grammar/quiz2.json
    - assets/data/toefl/grammar/quiz3.json
    - assets/data/toefl/grammar/quiz4.json
    - assets/data/toefl/grammar/quiz5.json
    - assets/data/ielts/reading/quiz1.json
    - assets/data/ielts/reading/quiz2.json
    - assets/data/ielts/reading/quiz3.json
    - assets/data/ielts/reading/quiz4.json
    - assets/data/ielts/reading/quiz5.json
    - assets/data/ielts/vocabulary/quiz1.json
    - assets/data/ielts/vocabulary/quiz2.json
    - assets/data/ielts/vocabulary/quiz3.json
    - assets/data/ielts/vocabulary/quiz4.json
    - assets/data/ielts/vocabulary/quiz5.json
    - assets/data/ielts/grammar/quiz1.json
    - assets/data/ielts/grammar/quiz2.json
    - assets/data/ielts/grammar/quiz3.json
    - assets/data/ielts/grammar/quiz4.json
    - assets/data/ielts/grammar/quiz5.json
    - assets/data/idioms/beginner/quiz1.json
    - assets/data/idioms/beginner/quiz2.json
    - assets/data/idioms/beginner/quiz3.json
    - assets/data/idioms/beginner/quiz4.json
    - assets/data/idioms/beginner/quiz5.json

    - assets/data/idioms/intermediate/quiz1.json
    - assets/data/idioms/intermediate/quiz2.json
    - assets/data/idioms/intermediate/quiz3.json
    - assets/data/idioms/intermediate/quiz4.json
    - assets/data/idioms/intermediate/quiz5.json
    - assets/data/idioms/advanced/quiz1.json
    - assets/data/idioms/advanced/quiz2.json
    - assets/data/idioms/advanced/quiz3.json
    - assets/data/idioms/advanced/quiz4.json
    - assets/data/idioms/advanced/quiz5.json


