name: english_quiz
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

#  assets:
#    - assets/images/
#    - assets/icons/
#    - assets/sounds/
##    - assets/data/vocabulary/beginner
#    - assets/data/grammar/
#    - assets/data/spelling/
#    - assets/data/kids/
#    - assets/data/reading/
#    - assets/data/phrasal_verbs/
#    - assets/data/
  assets:
    - assets/data/vocabulary/beginner/
    - assets/data/vocabulary/intermediate/
    - assets/data/vocabulary/advanced/
    - assets/data/phrasal_verbs/beginner/
    - assets/data/phrasal_verbs/intermediate/
    - assets/data/phrasal_verbs/advanced/
    - assets/data/reading/beginner/
    - assets/data/reading/intermediate/
    - assets/data/reading/advanced/
    - assets/data/grammar/beginner/
    - assets/data/grammar/intermediate/
    - assets/data/grammar/advanced/
